const img = (id, w = 1200) =>
  `https://images.unsplash.com/${id}?w=${w}&q=80&fm=auto&fit=crop`;

const P = {
  sofa1: img('photo-1555041469-a586c61ea9bc'),
  sofa2: img('photo-1493663284031-b7e3aefcae8e'),
  sofa3: img('photo-1567016432779-094069958ea5'),
  sofa4: img('photo-1583847268964-b28dc8f51f92'),
  living1: img('photo-1586023492125-27b2c045efd7'),
  living2: img('photo-1616486338812-3dadae4b4ace'),
  living3: img('photo-1618221195710-dd6b41faaea6'),
  living4: img('photo-1616486029423-aaa4789e8c9a'),
  living5: img('photo-1493809842364-78817add7ffb'),
  living6: img('photo-1522708323590-d24dbb6b0267'),
  living7: img('photo-1484101403633-562f891dc89a'),
  armchair: img('photo-1592078615290-033ee584e267'),
  chair: img('photo-1567538096630-e0c55bd6374c'),
  dining: img('photo-1533090481720-856c6e3c1fdc'),
  dining2: img('photo-1600585154340-be6161a56a0c'),
  bedroom: img('photo-1505693416388-ac5ce068fe85'),
  bedroom2: img('photo-1522771739844-6a9f6d5f14af'),
  bedroom3: img('photo-1584100936595-c0654b55a2e2'),
  bedroom4: img('photo-1513694203232-719a280e022f'),
  car1: img('photo-1503376780353-7e6692767b70'),
  car2: img('photo-1552519507-da3b142c6e3d'),
  car3: img('photo-1502877338535-766e1452684a'),
  fabric1: img('photo-1631679706909-1844bbd07221', 900),
  fabric2: img('photo-1620799140408-edc6dcb6d633', 900),
  fabric3: img('photo-1616627981207-91b1f47f3756', 900),
  fabric4: img('photo-1600334129128-685c5582fd35', 900),
  texture: img('photo-1616594039964-ae9021a400a0', 900),
};

export const placeholderSettings = {
  businessName: 'Trendz Upholstery',
  tagline: 'Custom Upholstery & Interiors',
  whatsappNumber: '919999999999',
  phoneNumber: '+91 99999 99999',
  email: 'hello@trendzupholstery.com',
  address: 'MG Road, Kochi, Kerala',
  businessHours: 'Mon – Sat: 9:00 AM – 7:00 PM',
  instagram: '',
  facebook: '',
  youtube: '',
  mapEmbedUrl: '',
  metaDescription:
    'Premium upholstery and custom furniture studio. Sofa sets, upholstery, curtains, seat covers and custom furniture crafted to fit your space.',
};

export const placeholderCategories = [
  { _id: 'c1', name: 'Sofa Sets', slug: 'sofa-sets', description: 'Complete sofa sets designed, customized and upholstered for your home.', image: P.sofa1 },
  { _id: 'c2', name: 'Sofa Upholstery', slug: 'sofa-upholstery', description: 'Give your existing sofa a completely new look.', image: P.sofa2 },
  { _id: 'c3', name: 'Curtains', slug: 'curtains', description: 'Custom curtains with carefully selected fabrics, colors and finishes.', image: P.bedroom4 },
  { _id: 'c4', name: 'Seat Covers', slug: 'seat-covers', description: 'Tailored seat covers designed for comfort, durability and style.', image: P.living2 },
  { _id: 'c5', name: 'Chairs', slug: 'chairs', description: 'Premium upholstery solutions for chairs and dining furniture.', image: P.chair },
  { _id: 'c6', name: 'Cushions', slug: 'cushions', description: 'Decorative and functional cushions made to match your interiors.', image: P.bedroom3 },
  { _id: 'c7', name: 'Custom Furniture', slug: 'custom-furniture', description: 'Unique furniture pieces built and upholstered to your specification.', image: P.living3 },
  { _id: 'c8', name: 'Car Interiors', slug: 'car-interiors', description: 'Custom-fit car seat covers with professional finishing.', image: P.car2 },
  { _id: 'c9', name: 'Headboards', slug: 'headboards', description: 'Tailored upholstered headboards for a complete bedroom look.', image: P.bedroom },
  { _id: 'c10', name: 'Other Works', slug: 'other-works', description: 'Specialized and custom upholstery projects.', image: P.living7 },
];

export const placeholderServices = [
  { _id: 's1', title: 'Sofa Sets', slug: 'sofa-sets', description: 'Complete sofa sets designed, customized and upholstered for your home.', features: ['Custom size and shape', 'Frame & cushioning', 'Fabric selection'], image: P.sofa1 },
  { _id: 's2', title: 'Curtains', slug: 'curtains', description: 'Custom curtains with carefully selected fabrics, colors and finishes.', features: ['Custom measurement', 'Lining & hardware', 'Sewing & finishing'], image: P.bedroom4 },
  { _id: 's3', title: 'Seat Covers', slug: 'seat-covers', description: 'Tailored seat covers designed for comfort, durability and style.', features: ['Perfect fit', 'Washable fabrics', 'Durable stitching'], image: P.living2 },
  { _id: 's4', title: 'Sofa Upholstery', slug: 'sofa-upholstery', description: 'Give your existing furniture a completely new look.', features: ['New fabric', 'Cushion replacement', 'Frame repair'], image: P.sofa2 },
  { _id: 's5', title: 'Custom Cushions', slug: 'custom-cushions', description: 'Decorative and functional cushions made to match your interiors.', features: ['Custom sizes', 'Variety of fabrics', 'Matching sets'], image: P.bedroom3 },
  { _id: 's6', title: 'Chair & Dining Upholstery', slug: 'chair-dining-upholstery', description: 'Premium upholstery solutions for chairs and dining furniture.', features: ['Dining chairs', 'Office chairs', 'Recliners'], image: P.chair },
  { _id: 's7', title: 'Car Seat Covers', slug: 'car-seat-covers', description: 'Custom-fit seat covers with professional finishing.', features: ['Custom fit', 'Quality material', 'Easy install'], image: P.car2 },
  { _id: 's8', title: 'Custom Projects', slug: 'custom-projects', description: 'Unique upholstery solutions based on your requirements.', features: ['Any project size', 'Fabric matching', 'On-site work'], image: P.living3 },
];

export const placeholderMaterials = [
  { _id: 'm1', name: 'Premium Velvet', slug: 'premium-velvet', description: 'Soft texture with a luxurious appearance, ideal for statement sofas and accent chairs.', colors: ['Navy', 'Mustard', 'Forest', 'Blush'], image: P.fabric4 },
  { _id: 'm2', name: 'Linen', slug: 'linen', description: 'Breathable, natural weave with a relaxed and timeless look.', colors: ['Cream', 'Beige', 'Grey', 'White'], image: P.fabric1 },
  { _id: 'm3', name: 'Cotton', slug: 'cotton', description: 'Soft, versatile and easy to live with. A dependable everyday choice.', colors: ['White', 'Beige', 'Olive', 'Navy'], image: P.fabric2 },
  { _id: 'm4', name: 'Leather', slug: 'leather', description: 'Full-grain and bonded leather options for a refined, long-lasting finish.', colors: ['Tan', 'Black', 'Cognac', 'Brown'], image: P.living4 },
  { _id: 'm5', name: 'Suede', slug: 'suede', description: 'Soft, matte texture with an understated, premium feel.', colors: ['Charcoal', 'Grey', 'Sand', 'Terracotta'], image: P.fabric3 },
  { _id: 'm6', name: 'Textured Fabric', slug: 'textured-fabric', description: 'Woven textures that add depth and character to any piece.', colors: ['Grey', 'Beige', 'Rust', 'Charcoal'], image: P.texture },
  { _id: 'm7', name: 'Performance Fabric', slug: 'performance-fabric', description: 'Stain-resistant and durable, made for busy homes and daily use.', colors: ['Beige', 'Grey', 'Navy', 'Mustard'], image: P.living5 },
  { _id: 'm8', name: 'Custom Fabric', slug: 'custom-fabric', description: 'Bring your own fabric or let us source a unique material for you.', colors: ['Any color', 'Any texture', 'Any print'], image: P.fabric2 },
];

export const placeholderCollections = [
  { _id: 'k1', name: 'Contemporary', slug: 'contemporary', tagline: 'Clean lines, current forms', description: "Modern silhouettes in refined neutral tones for today's living spaces.", image: P.living3 },
  { _id: 'k2', name: 'Classic', slug: 'classic', tagline: 'Timeless elegance', description: 'Traditional shapes and detailing, made to feel right at home.', image: P.sofa1 },
  { _id: 'k3', name: 'Minimal', slug: 'minimal', tagline: 'Less, but better', description: 'Quiet forms and simple silhouettes for calm, uncluttered interiors.', image: P.living2 },
  { _id: 'k4', name: 'Luxury', slug: 'luxury', tagline: 'Refined materials', description: 'Rich textures, tailored finishes and premium fabrics.', image: P.living1 },
  { _id: 'k5', name: 'Modern', slug: 'modern', tagline: 'Designed for today', description: 'Bold, current designs with comfort built in.', image: P.living6 },
  { _id: 'k6', name: 'Custom', slug: 'custom', tagline: 'Made your way', description: 'Your dimensions, your fabrics, your vision — crafted to fit.', image: P.living7 },
];

export const placeholderTestimonials = [
  { _id: 't1', customerName: 'Anjali Menon', service: 'Sofa Upholstery', rating: 5, review: 'Excellent finishing and very professional work. The sofa looks completely new — even better than the day we bought it.' },
  { _id: 't2', customerName: 'Rahul Nair', service: 'Custom Sofa Set', rating: 5, review: 'They designed and built a complete sofa set for our new living room. Perfect fit, premium fabric and delivered on time.' },
  { _id: 't3', customerName: 'Priya Thomas', service: 'Curtains', rating: 5, review: 'Beautiful stitching and great fabric selection advice. The curtains transformed the entire look of our hall.' },
  { _id: 't4', customerName: 'Suresh Pillai', service: 'Car Seat Covers', rating: 5, review: 'Custom-fit covers with excellent finishing. The team measured everything and the fit is perfect.' },
  { _id: 't5', customerName: 'Divya Krishnan', service: 'Cushions', rating: 5, review: 'Lovely custom cushions made to match my living room colour scheme. Great attention to detail.' },
  { _id: 't6', customerName: 'Arjun Varma', service: 'Dining Chair Upholstery', rating: 5, review: 'Very reliable and reasonably priced. All six dining chairs reupholstered beautifully.' },
];

const g = (url, alt, title, category, featured = false) => ({ _id: Math.random().toString(36).slice(2), url, alt, title, category, featured });

export const placeholderGallery = [
  g(P.sofa1, 'Modern beige sofa set', 'Modern L-Shape Sofa', 'Sofa Sets', true),
  g(P.sofa2, 'Navy velvet reupholstered sofa', 'Reupholstered Sofa', 'Sofa Upholstery', true),
  g(P.living1, 'Luxury living room', 'Luxury Living Room', 'Custom Furniture'),
  g(P.living2, 'Minimal living room', 'Minimal Living Room', 'Seat Covers'),
  g(P.living3, 'Modern corner sofa', 'Corner Sofa', 'Custom Furniture', true),
  g(P.chair, 'Upholstered dining chair', 'Dining Chair', 'Chairs'),
  g(P.armchair, 'Accent armchair', 'Accent Armchair', 'Chairs'),
  g(P.bedroom, 'Upholstered headboard', 'Headboard', 'Headboards'),
  g(P.bedroom4, 'Curtains in a bedroom', 'Custom Curtains', 'Curtains'),
  g(P.car2, 'Custom car seat covers', 'Car Seat Covers', 'Car Interiors'),
  g(P.bedroom3, 'Cushion collection on bed', 'Cushion Collection', 'Cushions'),
  g(P.living6, 'Velvet sofa set', 'Velvet Sofa Set', 'Sofa Sets'),
];

export const placeholderProjects = [
  {
    _id: 'p1',
    title: 'Modern L-Shape Sofa Set',
    slug: 'modern-l-shape-sofa-set',
    categoryName: 'Sofa Sets',
    description: 'Complete L-shape sofa set designed and upholstered in premium textured fabric with deep, supportive cushioning and custom stitching details.',
    location: 'Panampilly Nagar, Kochi',
    materials: 'Solid hardwood frame, high-density foam',
    fabric: 'Premium textured fabric',
    color: 'Beige',
    services: ['Custom sofa set', 'Cushioning', 'Tailored finishing'],
    coverImage: P.sofa1,
    beforeImage: P.sofa3,
    afterImage: P.sofa1,
    galleryImages: [{ url: P.living1, alt: '' }, { url: P.living2, alt: '' }, { url: P.living3, alt: '' }],
    featured: true,
    published: true,
    completionDate: '2026-03-15',
    createdAt: '2026-03-15',
  },
  {
    _id: 'p2',
    title: 'Complete Reupholstery — Living Room Sofa',
    slug: 'complete-reupholstery-living-room-sofa',
    categoryName: 'Sofa Upholstery',
    description: 'Complete transformation of an existing sofa set using premium fabric, new cushioning and custom finishing.',
    location: 'Kakkanad, Kochi',
    materials: 'Foam replacement, webbing',
    fabric: 'Velvet',
    color: 'Navy',
    services: ['Complete reupholstery', 'Cushion replacement'],
    coverImage: P.sofa2,
    beforeImage: P.living7,
    afterImage: P.sofa2,
    galleryImages: [{ url: P.living4, alt: '' }, { url: P.living5, alt: '' }],
    featured: true,
    published: true,
    completionDate: '2026-02-20',
    createdAt: '2026-02-20',
  },
  {
    _id: 'p3',
    title: 'Elegant Curtains with Sheer Lining',
    slug: 'elegant-curtains-with-sheer-lining',
    categoryName: 'Curtains',
    description: 'Floor-to-ceiling curtains with sheer lining, custom-stitched to fit the space perfectly.',
    location: 'Edapally, Kochi',
    materials: 'Cotton blend with sheer lining',
    fabric: 'Cotton blend',
    color: 'Cream',
    services: ['Curtain sewing', 'Lining', 'Hardware fitting'],
    coverImage: P.bedroom4,
    galleryImages: [{ url: P.bedroom, alt: '' }, { url: P.bedroom3, alt: '' }],
    published: true,
    completionDate: '2026-01-30',
    createdAt: '2026-01-30',
  },
  {
    _id: 'p4',
    title: 'Tailored Car Seat Covers',
    slug: 'tailored-car-seat-covers',
    categoryName: 'Car Interiors',
    description: 'Custom-fit car seat covers stitched and installed with a professional, seamless finish.',
    location: 'Fort Kochi',
    materials: 'Leatherette with breathable mesh',
    fabric: 'Leatherette',
    color: 'Black',
    services: ['Car seat covers', 'Installation'],
    coverImage: P.car2,
    galleryImages: [{ url: P.car1, alt: '' }, { url: P.car3, alt: '' }],
    published: true,
    completionDate: '2026-02-10',
    createdAt: '2026-02-10',
  },
  {
    _id: 'p5',
    title: 'Custom Dining Chair Upholstery',
    slug: 'custom-dining-chair-upholstery',
    categoryName: 'Chairs',
    description: 'Six dining chairs reupholstered with stain-resistant performance fabric and refreshed foam seating.',
    location: 'Marine Drive, Kochi',
    materials: 'Performance fabric, new foam',
    fabric: 'Performance fabric',
    color: 'Grey',
    services: ['Chair upholstery', 'Foam refresh'],
    coverImage: P.chair,
    beforeImage: P.dining,
    afterImage: P.chair,
    galleryImages: [{ url: P.dining2, alt: '' }, { url: P.chair, alt: '' }],
    published: true,
    completionDate: '2026-01-18',
    createdAt: '2026-01-18',
  },
  {
    _id: 'p6',
    title: 'Upholstered Headboard & Bedroom Set',
    slug: 'upholstered-headboard-bedroom-set',
    categoryName: 'Headboards',
    description: 'Custom upholstered headboard with piped detail, matched with cushioning and fabric across the room.',
    location: 'Vyttila, Kochi',
    materials: 'MDF base, foam, premium velvet',
    fabric: 'Velvet',
    color: 'Terracotta',
    services: ['Headboard upholstery', 'Cushion set'],
    coverImage: P.bedroom,
    galleryImages: [{ url: P.bedroom2, alt: '' }, { url: P.bedroom3, alt: '' }],
    published: true,
    completionDate: '2025-12-22',
    createdAt: '2025-12-22',
  },
  {
    _id: 'p7',
    title: 'Recliner Reupholstery',
    slug: 'recliner-reupholstery',
    categoryName: 'Sofa Upholstery',
    description: 'Full reupholstery of a recliner with durable leather-look fabric, keeping the mechanism intact.',
    location: 'Palarivattom, Kochi',
    materials: 'Leather-look fabric',
    fabric: 'Leatherette',
    color: 'Cognac',
    services: ['Recliner upholstery', 'Mechanism service'],
    coverImage: P.living4,
    galleryImages: [{ url: P.living1, alt: '' }, { url: P.armchair, alt: '' }],
    published: true,
    completionDate: '2025-11-12',
    createdAt: '2025-11-12',
  },
  {
    _id: 'p8',
    title: 'Luxury Velvet Sofa Set',
    slug: 'luxury-velvet-sofa-set',
    categoryName: 'Sofa Sets',
    description: 'Statement velvet sofa set with deep button detailing, built to order for a premium living room.',
    location: 'Infopark, Kochi',
    materials: 'Hardwood frame, high-resilience foam',
    fabric: 'Velvet',
    color: 'Mustard',
    services: ['Custom sofa set', 'Button detailing'],
    coverImage: P.living6,
    galleryImages: [{ url: P.living3, alt: '' }, { url: P.living5, alt: '' }],
    featured: true,
    published: true,
    completionDate: '2026-04-05',
    createdAt: '2026-04-05',
  },
  {
    _id: 'p9',
    title: 'Custom Cushion Collection',
    slug: 'custom-cushion-collection',
    categoryName: 'Cushions',
    description: 'A matching collection of decorative and functional cushions in custom sizes and fabrics.',
    location: 'Chottanikkara, Kochi',
    materials: 'Cotton and linen blends',
    fabric: 'Cotton & linen',
    color: 'Olive',
    services: ['Custom cushions', 'Covers & inserts'],
    coverImage: P.bedroom3,
    galleryImages: [{ url: P.fabric1, alt: '' }, { url: P.bedroom, alt: '' }],
    published: true,
    completionDate: '2026-02-28',
    createdAt: '2026-02-28',
  },
  {
    _id: 'p10',
    title: 'Bespoke Corner Sofa',
    slug: 'bespoke-corner-sofa',
    categoryName: 'Custom Furniture',
    description: "Corner sofa built from scratch to the client's exact dimensions and fabric choice.",
    location: 'Tripunithura, Kochi',
    materials: 'Engineered wood frame, foam',
    fabric: 'Linen',
    color: 'Cream',
    services: ['Custom furniture', 'Upholstery', 'Delivery & install'],
    coverImage: P.living3,
    galleryImages: [{ url: P.living2, alt: '' }, { url: P.sofa1, alt: '' }],
    published: true,
    completionDate: '2026-03-25',
    createdAt: '2026-03-25',
  },
  {
    _id: 'p11',
    title: 'Fabric Seat Covers for Home',
    slug: 'fabric-seat-covers-for-home',
    categoryName: 'Seat Covers',
    description: 'Tailored fabric seat covers for a living room sofa, removable and washable.',
    location: 'Kalamassery, Kochi',
    materials: 'Washable cotton',
    fabric: 'Cotton',
    color: 'Grey',
    services: ['Seat covers', 'Custom fitting'],
    coverImage: P.living2,
    galleryImages: [{ url: P.living5, alt: '' }, { url: P.living1, alt: '' }],
    published: true,
    completionDate: '2026-01-05',
    createdAt: '2026-01-05',
  },
  {
    _id: 'p12',
    title: 'Studio Transformation — Full Living Room',
    slug: 'studio-transformation-full-living-room',
    categoryName: 'Other Works',
    description: 'End-to-end interior upholstery: sofa, armchairs, curtains and cushions across one living space.',
    location: 'Kochi',
    materials: 'Mixed premium fabrics',
    fabric: 'Various',
    color: 'Mixed neutrals',
    services: ['Interior upholstery', 'Curtains', 'Cushions'],
    coverImage: P.living7,
    galleryImages: [{ url: P.living1, alt: '' }, { url: P.living4, alt: '' }, { url: P.living5, alt: '' }],
    featured: true,
    published: true,
    completionDate: '2026-04-18',
    createdAt: '2026-04-18',
  },
];
