export const placeholderEnquiries = [
  {
    _id: 'e1',
    name: 'Meera Joseph',
    phone: '+91 98470 12345',
    email: 'meera.j@example.com',
    service: 'Sofa Upholstery',
    description:
      'We have a 3-seater fabric sofa that is 6 years old. The fabric has faded and the cushions have gone flat. We would like to reupholster it in a darker colour.',
    budget: '₹10,000 – ₹25,000',
    material: 'Velvet',
    contactMethod: 'phone',
    images: [],
    status: 'New',
    adminNotes: '',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'e2',
    name: 'Vishnu Prasad',
    phone: '+91 98955 67890',
    email: '',
    service: 'Curtains',
    description:
      'Need floor-to-ceiling curtains for 3 windows in our living room. Around 12 feet total width. Looking for a cream or beige fabric with lining.',
    budget: 'Under ₹10,000',
    material: 'Cotton blend',
    contactMethod: 'whatsapp',
    images: [],
    status: 'Contacted',
    adminNotes: 'Sent quotation on 12 Jan. Awaiting confirmation.',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    _id: 'e3',
    name: 'Anita Menon',
    phone: '+91 94470 55678',
    email: 'anita.menon@example.com',
    service: 'Car Seat Covers',
    description:
      'Toyota Innova (2022 model). Need full custom seat covers in black leatherette. Please let me know the price and how long it takes.',
    budget: '₹25,000 – ₹50,000',
    material: 'Leatherette',
    contactMethod: 'phone',
    images: [],
    status: 'Contacted',
    adminNotes: '',
    createdAt: new Date(Date.now() - 6 * 86400000).toISOString(),
  },
  {
    _id: 'e4',
    name: 'Thomas Kurian',
    phone: '+91 98460 11223',
    email: 't.kurian@example.com',
    service: 'Custom Furniture',
    description:
      'We are building a new home and need a custom L-shaped corner sofa (9 feet by 6 feet) with storage. Can you help with design suggestions?',
    budget: 'Above ₹1,00,000',
    material: 'Linen',
    contactMethod: 'email',
    images: [],
    status: 'Completed',
    adminNotes: 'Site measurement done. Fabric samples shared.',
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
];
